export const textSettingsScreen = {
  title: '設定',
  account: 'アカウント',
  login: 'ログイン',
  signup: '新規アカウントを作成',
  logout: 'ログアウト',
  security: 'セキュリティ',
  changePassword: 'パスワードを変更',
  changeEmail: 'メールアドレスを変更',
  privacy: 'プライバシー設定',
  deleteAccount: 'アカウントを削除',
  general: '一般',
  notifications: '通知',
  theme: 'テーマ',
  language: '言語',
  support: 'サポート',
  help: 'ヘルプ',
  contact: 'お問い合わせ',
  feedback: 'フィードバック',
  about: 'アプリについて',
  version: 'バージョン',
  termsOfService: '利用規約',
  privacyPolicy: 'プライバシーポリシー',
  licenses: 'ライセンス',
};
