name: Deploy

on:
  push:
    branches: [main]

jobs:
  # ステージング環境へのデプロイ
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build for staging
        run: npx expo export:web

      - name: Deploy to Expo (staging)
        run: npx expo publish --release-channel staging

      - name: Upload staging build
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: web-build/
          retention-days: 7
