name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # PRの品質チェック
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Check for console.log statements
        run: |
          if grep -r "console\.log" app/ components/ hooks/ constants/ --include="*.ts" --include="*.tsx"; then
            echo "Warning: console.log statements found in production code"
            exit 1
          fi

  # セキュリティチェック
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Check for sensitive data
        run: |
          # 実際の機密情報のパターンを検出（変数代入や文字列リテラル）
          if grep -r -E "(password\s*=|secret\s*=|token\s*=|api_key\s*=|private_key\s*=)" app/ components/ hooks/ constants/ --include="*.ts" --include="*.tsx" | grep -v -E "(//|/\*|console\.log|example|test|mock)"; then
            echo "Warning: Potential sensitive data found in code"
            exit 1
          fi

          # ハードコードされた機密情報の検出
          if grep -r -E "['\"][a-zA-Z0-9]{32,}['\"]" app/ components/ hooks/ constants/ --include="*.ts" --include="*.tsx" | grep -v -E "(//|/\*|example|test|mock)"; then
            echo "Warning: Potential hardcoded secrets found in code"
            exit 1
          fi
